name: Test Schema validation

on:
  workflow_dispatch:

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate
      id: validation
      uses: ammarlakis/action-ajv@master
      with:
        data: data.yml
        schemas: schema.yml
    - name: Show outputs
      run: |
        echo ${{ steps.validation.outputs.valid }}
        echo ${{ steps.validation.outputs.errors }}
